db-path: ./events_db.db
node-url: "wss://ethereum-rpc.publicnode.com" # e.g."wss://mainnet.infura.io/ws/v3/***"
event-info:
  event:
    name: "Transfer"
    inputs:
      - indexed: true
        name: from
        type: address
      - indexed: true
        name: to
        type: address
      - indexed: false
        name: value
        type: uint256
    anonymous: false
  contract: "0xdAC17F958D2ee523a2206206994597C13D831ec7"
  block-filter:
    kind: "range"
    from-block: "latest"
    # to-block: "23096181"
